server:
  port: 8080
  forward-headers-strategy: native

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BookingService"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "namhoang0505pro@gmail.com"
    password: "mzaz jytw mhcf ghci"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

jwt:
  signerKey: "3aF+lAiyA/tEAeeBtmlou0RwdTwXx0lU6SjH0MYBR7DRt9vyJzlv66uqnqHMP2NW"
  valid-duration: 3600
  refreshable-duration: 36000

beautya:
  feedback:
    link: http://localhost:8080/BookingService/api/feedbacks

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html




